const LANGUAGE_NAMES = {
  ru: 'Russian',
  en: 'English',
  uk: 'Ukrainian'
};

function buildSystemPrompt(language = 'ru', deep = false) {
  const languageName = LANGUAGE_NAMES[language] || LANGUAGE_NAMES.ru;
  const depthRules = deep
    ? 'This is a paid DEEP SCAN. Make it richer than a regular scan: use exactly the requested deep scan title for the language, label "DEEP SCAN", 5-7 vibe parameters, detailedAnalysis, roast, advice and shareText.'
    : 'This is a regular scan. Keep it compact.';
  return `
You are SnarkScan AI, an entertainment-only Telegram Mini App.
Create playful, meme-like vibe scans in ${languageName}. Be witty, social, viral, and safe.
Never claim objective beauty, mental health, identity, age, ethnicity, income, sexuality, medical state or criminal traits.
Avoid harassment, cruelty, sexualization, hate, or vulnerable-attribute guessing.
${depthRules}
Return ONLY valid JSON with this shape:
{
  "deep": boolean,
  "label": string,
  "title": string,
  "vibeName": string,
  "score": number,
  "percentages": [{"label": string, "value": number}],
  "detailedAnalysis": string,
  "roast": string,
  "advice": string,
  "shareText": string,
  "disclaimer": string,
  "upsell": string
}
`;
}

function buildUserPrompt({ mode, text, language, deep }) {
  const modeMap = {
    photo: 'Analyze the uploaded image as a funny entertainment vibe scan. Do not identify or infer sensitive traits.',
    roast: 'Create a playful roast based on the user input. Keep it teasing, not cruel.',
    chat: 'Analyze the pasted chat/message as entertainment: interest level, red flags, suggested reply. Do not overclaim.',
    compare: 'Compare two vibes as a funny entertainment result. Do not rank beauty or objective worth.'
  };

  const deepTitle = {
    ru: 'Title must be: "Глубокий скан завершён".',
    en: 'Title must be: "Deep scan complete".',
    uk: 'Title must be: "Глибокий скан завершено".'
  };

  return `${modeMap[mode] || modeMap.photo}\nOutput language: ${LANGUAGE_NAMES[language] || LANGUAGE_NAMES.ru}.\n${deep ? deepTitle[language] : ''}\nUser text/context: ${text || 'No text provided.'}`;
}

export async function createOpenAIScan({ apiKey, model, mode, text, imageDataUrl, language = 'ru', deep = false }) {
  if (!apiKey) throw new Error('OPENAI_API_KEY is missing');
  const safeLanguage = ['ru', 'en', 'uk'].includes(language) ? language : 'ru';

  const userContent = [{ type: 'input_text', text: buildUserPrompt({ mode, text, language: safeLanguage, deep }) }];
  if (imageDataUrl && (mode === 'photo' || mode === 'compare')) {
    userContent.push({ type: 'input_image', image_url: imageDataUrl });
  }

  const response = await fetch('https://api.openai.com/v1/responses', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${apiKey}`
    },
    body: JSON.stringify({
      model: model || 'gpt-4.1-mini',
      input: [
        { role: 'system', content: [{ type: 'input_text', text: buildSystemPrompt(safeLanguage, deep) }] },
        { role: 'user', content: userContent }
      ],
      temperature: 0.9
    })
  });

  const data = await response.json();
  if (!response.ok) {
    throw new Error(data?.error?.message || 'OpenAI request failed');
  }

  const outputText = data.output_text || data.output?.flatMap(item => item.content || [])
    .find(item => item.type === 'output_text')?.text;

  if (!outputText) throw new Error('OpenAI returned no text output');

  try {
    return JSON.parse(outputText);
  } catch {
    const fallbackByLanguage = {
      ru: {
        title: 'AI выдал вайб, но JSON решил жить отдельно.',
        vibeName: 'хаотичный прототип',
        roast: outputText.slice(0, 240),
        advice: 'Повтори скан или переключись на mock-режим для теста.',
        shareText: 'SnarkScan AI уже работает, но AI слишком драматично ответил.',
        disclaimer: 'Результат создан AI для развлечения.',
        upsell: 'Глубокий скан будет доступен в платной версии.'
      },
      en: {
        title: 'AI found the vibe, but JSON chose chaos.',
        vibeName: 'chaotic prototype',
        roast: outputText.slice(0, 240),
        advice: 'Try scanning again or switch to mock mode for testing.',
        shareText: 'SnarkScan AI works, but the AI answered with too much drama.',
        disclaimer: 'Result generated by AI for entertainment.',
        upsell: 'Deep scan will be available in the paid version.'
      },
      uk: {
        title: 'ШІ видав вайб, але JSON вирішив жити окремо.',
        vibeName: 'хаотичний прототип',
        roast: outputText.slice(0, 240),
        advice: 'Повтори скан або перемкнись у тестовий режим.',
        shareText: 'SnarkScan AI вже працює, але ШІ відповів занадто драматично.',
        disclaimer: 'Результат створений ШІ для розваги.',
        upsell: 'Глибокий скан буде доступний у платній версії.'
      }
    };
    return {
      ...fallbackByLanguage[safeLanguage],
      score: 77,
      percentages: [
        { label: safeLanguage === 'en' ? 'vibe' : 'вайб', value: 44 },
        { label: safeLanguage === 'en' ? 'chaos' : 'хаос', value: 31 },
        { label: safeLanguage === 'en' ? 'intrigue' : 'інтрига', value: 25 }
      ]
    };
  }
}
